---

- name: Check OS version and family
  ansible.builtin.fail:
      msg: "This role can only be run against Ubuntu 22|24. {{ ansible_facts.distribution | default('') }} {{ ansible_facts.distribution_major_version | default('') }} is not supported."
  when:
      - (ansible_facts.distribution | default('')) == 'Ubuntu'
      - (ansible_facts.distribution_major_version | default('')) is version_compare('22', '!=')
      - (ansible_facts.distribution_major_version | default('')) is version_compare('24', '!=')
  tags:
      - security

- name: Check ansible version
  ansible.builtin.assert:
      that: ansible_version.full is version_compare(min_ansible_version, '>=')
      fail_msg: "You must use Ansible {{ min_ansible_version }} or greater"
      success_msg: "This role is running a supported version of ansible {{ ansible_version.full }} >= {{ min_ansible_version }}"
  tags:
      - security

#  This control should always run as this can pass on unintended issues.
- name: "Check password set for connecting user"
  block:
      - name: Capture current password state of connecting user"
        ansible.builtin.shell: "grep -w {{ ansible_env.SUDO_USER }} /etc/shadow | awk -F: '{print $2}'"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ansible_user_password_set

      - name: "Assert that password set for {{ ansible_env.SUDO_USER }} and account not locked"
        ansible.builtin.assert:
            that: ansible_user_password_set.stdout != "!!" and ansible_user_password_set.stdout | length > 10
            fail_msg: "You have {{ sudo_password_rule }} enabled but the user = {{ ansible_env.SUDO_USER }} has no password set - It can break access"
            success_msg: "You have a password set for sudo user {{ ansible_env.SUDO_USER }}"
        vars:
            sudo_password_rule: ubtu22cis_rule_5_3_4  # pragma: allowlist secret
  when:
      - ubtu22cis_rule_5_3_4
      - ansible_env.SUDO_USER is defined
  tags:
      - security

- name: Gather the package facts before prelim
  ansible.builtin.package_facts:
      manager: auto
  tags:
      - security

- name: Run prelim tasks
  ansible.builtin.import_tasks:
      file: prelim.yml
  tags:
      - prelim_tasks
      - security

- name: Gather the package facts after prelim
  ansible.builtin.package_facts:
      manager: auto
  tags:
      - security

- name: Run parse /etc/passwd
  ansible.builtin.import_tasks:
      file: parse_etc_password.yml
  when:
      - ubtu22cis_section5 or
        ubtu22cis_section6
  tags:
      - security

- name: Gather the package facts
  ansible.builtin.package_facts:
      manager: auto
  tags:
      - security

- name: Include section 1 patches
  ansible.builtin.import_tasks:
      file: section_1/main.yml
  when: ubtu22cis_section1
  tags:
      - section1

- name: Include section 2 patches
  ansible.builtin.import_tasks:
      file: section_2/main.yml
  when: ubtu22cis_section2
  tags:
      - section2

- name: Include section 3 patches
  ansible.builtin.import_tasks:
      file: section_3/main.yml
  when: ubtu22cis_section3
  tags:
      - section3

- name: Include section 4 patches
  ansible.builtin.import_tasks:
      file: section_4/main.yml
  when: ubtu22cis_section4
  tags:
      - section4

- name: Include section 5 patches
  ansible.builtin.import_tasks: section_5/main.yml
  when: ubtu22cis_section5
  tags:
      - section5

- name: Include section 6 patches
  ansible.builtin.import_tasks:
      file: section_6/main.yml
  when: ubtu22cis_section6
  tags:
      - section6

- name: Run auditd logic
  ansible.builtin.import_tasks:
      file: auditd.yml
  when: update_audit_template
  tags:
      - security

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Reboot system
  block:
      - name: Reboot system if not skipped
        ansible.builtin.reboot:
        when:
            - not skip_reboot
            - change_requires_reboot

      - name: Warning a reboot required but skip option set
        ansible.builtin.debug:
            msg: "Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results"
        changed_when: true
        when:
            - skip_reboot
            - change_requires_reboot


- name: If Warnings found Output count and control IDs affected
  ansible.builtin.debug:
      msg: "You have {{ warn_count }} Warning(s) that require investigating that are related to the following benchmark ID(s) {{ warn_control_list }}"
  when: warn_count != 0
  tags:
      - security

- name: Include security agents
  import_tasks: security_agents/main.yml
  when: ubtu22cis_secagents_patch
  tags:
      - secagents
